import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Field, FormSection } from './workspace/FormControls'

export default function BeamForm({ onSubmit, disabled }) {
  const { t } = useTranslation(); const [values, setValues] = useState({ type: 'Normal', fc: '25', fy: '420', width: '', depth: '', length: '', cover: '3', rebarCount: '', rebarDiameter: '', dead: '', live: '', wind: '', snow: '' })
  const set = key => event => setValues(current => ({ ...current, [key]: event.target.value }))
  const submit = event => { event.preventDefault(); onSubmit({ type: values.type, fc: Number(values.fc), fy: Number(values.fy), width: Number(values.width), depth: Number(values.depth), length: Number(values.length), cover: Number(values.cover), rebar: { count: Number(values.rebarCount), diameter: Number(values.rebarDiameter) }, loads: { dead: Number(values.dead) || 0, live: Number(values.live) || 0, wind: Number(values.wind) || 0, snow: Number(values.snow) || 0 } }) }
  const loads = ['dead', 'live', 'wind', 'snow']
  return <form onSubmit={submit}><FormSection title={t('forms.geometry_material')}><Field label={t('forms.beam_type')}><select value={values.type} onChange={set('type')}><option value="Normal">Normal</option><option value="Inverted">Inverted</option><option value="Tee">Tee</option><option value="Prestressed">Prestressed</option></select></Field><Field label={t('forms.concrete_strength')}><input required type="number" min="0.01" step="0.01" value={values.fc} onChange={set('fc')} /></Field><Field label={t('forms.steel_strength')}><input required type="number" min="0.01" step="0.01" value={values.fy} onChange={set('fy')} /></Field><Field label={t('forms.beam_width')}><input required type="number" min="0.01" step="0.01" value={values.width} onChange={set('width')} /></Field><Field label={t('forms.beam_depth')}><input required type="number" min="0.01" step="0.01" value={values.depth} onChange={set('depth')} /></Field><Field label={t('forms.beam_span_m')}><input required type="number" min="0.01" step="0.01" value={values.length} onChange={set('length')} /></Field><Field label={t('forms.rebar_count')}><input required type="number" min="1" step="1" value={values.rebarCount} onChange={set('rebarCount')} /></Field><Field label={t('forms.bar_diameter')}><input required type="number" min="0.01" step="0.01" value={values.rebarDiameter} onChange={set('rebarDiameter')} /></Field><Field label={t('forms.cover')}><input required type="number" min="0" step="0.1" value={values.cover} onChange={set('cover')} /></Field></FormSection><FormSection title={t('forms.line_loads')}>{loads.map(key => <Field key={key} label={t(`forms.${key}`)}><input type="number" step="0.01" value={values[key]} onChange={set(key)} /></Field>)}</FormSection><div className="form-actions"><button className="button button-primary" type="submit" disabled={disabled}>{disabled ? t('common.analyzing') : t('forms.run_beam')}</button></div></form>
}
