import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Field, FormSection } from './workspace/FormControls'

export default function ColumnForm({ onSubmit, disabled }) {
  const { t } = useTranslation(); const [v, setV] = useState({ type:'Rectangular', b:'', h:'', L:'', phi:'', nBars:'', s:'', fc:'25', fy:'420', axial:'', moment:'' })
  const set = key => e => setV(x => ({...x,[key]:e.target.value})); const submit = e => { e.preventDefault(); onSubmit({ type:v.type, geometry:{b:Number(v.b),h:Number(v.h),L:Number(v.L)}, reinforcement:{barDiameter:Number(v.phi),barCount:Number(v.nBars),tieSpacing:Number(v.s)}, materials:{fc:Number(v.fc),fy:Number(v.fy)}, loads:{axial:Number(v.axial)||0,moment:Number(v.moment)||0} }) }
  return <form onSubmit={submit}><FormSection title={t('forms.geometry_reinforcement')}><Field label={t('forms.column_type')}><select value={v.type} onChange={set('type')}><option>Rectangular</option><option>Circular</option><option>Composite</option></select></Field><Field label={t('forms.width_cm')}><input required type="number" min="0.01" step="any" value={v.b} onChange={set('b')} /></Field><Field label={t('forms.depth_cm')}><input required type="number" min="0.01" step="any" value={v.h} onChange={set('h')} /></Field><Field label={t('forms.height_m')}><input required type="number" min="0.01" step="any" value={v.L} onChange={set('L')} /></Field><Field label={t('forms.bar_diameter')}><input required type="number" min="0.01" step="any" value={v.phi} onChange={set('phi')} /></Field><Field label={t('forms.rebar_count')}><input required type="number" min="1" step="1" value={v.nBars} onChange={set('nBars')} /></Field><Field label={t('forms.tie_spacing')}><input required type="number" min="0.01" step="any" value={v.s} onChange={set('s')} /></Field><Field label={t('forms.concrete_strength')}><input required type="number" min="0.01" step="any" value={v.fc} onChange={set('fc')} /></Field><Field label={t('forms.steel_strength')}><input required type="number" min="0.01" step="any" value={v.fy} onChange={set('fy')} /></Field></FormSection><FormSection title={t('forms.actions')}><Field label={t('forms.axial_load')}><input required type="number" min="0" value={v.axial} onChange={set('axial')} /></Field><Field label={t('forms.moment')}><input type="number" value={v.moment} onChange={set('moment')} /></Field></FormSection><div className="form-actions"><button className="button button-primary" disabled={disabled}>{disabled?t('common.analyzing'):t('forms.run_column')}</button></div></form>
}
