import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Field, FormSection } from './workspace/FormControls'

export default function SlabForm({ onSubmit, disabled }) {
  const { t } = useTranslation(); const [v,setV]=useState({type:'solid',thickness:'',length:'',width:'',fc:'25',fy:'420',barDiameter:'',top:'',bottom:'',block:'',ribWidth:'',ribSpacing:'',dead:'',live:'',wind:'',snow:''}); const set=k=>e=>setV(x=>({...x,[k]:e.target.value}))
  const submit=e=>{e.preventDefault();const data={type:v.type,thickness:Number(v.thickness),length:Number(v.length),width:Number(v.width),fc:Number(v.fc),fy:Number(v.fy),barDiameter:Number(v.barDiameter),bottomBarCount:Number(v.bottom),loads:{dead:Number(v.dead)||0,live:Number(v.live)||0,wind:Number(v.wind)||0,snow:Number(v.snow)||0}};if(v.type==='solid')data.topBarCount=Number(v.top);if(v.type==='hollow')data.block={height:Number(v.block)};if(v.type==='waffle')data.waffle={ribWidth:Number(v.ribWidth),ribSpacing:Number(v.ribSpacing)};onSubmit(data)}
  return <form onSubmit={submit}><FormSection title={t('forms.geometry_material')}><Field label={t('forms.slab_type')}><select value={v.type} onChange={set('type')}><option value="solid">Solid</option><option value="hollow">Hollow</option><option value="waffle">Waffle</option></select></Field><Field label={t('forms.thickness_cm')}><input required type="number" min="0.01" step="any" value={v.thickness} onChange={set('thickness')}/></Field><Field label={t('forms.length_m')}><input required type="number" min="0.01" step="any" value={v.length} onChange={set('length')}/></Field><Field label={t('forms.width_m')}><input required type="number" min="0.01" step="any" value={v.width} onChange={set('width')}/></Field><Field label={t('forms.concrete_strength')}><input required type="number" min="0.01" step="any" value={v.fc} onChange={set('fc')}/></Field><Field label={t('forms.steel_strength')}><input required type="number" min="0.01" step="any" value={v.fy} onChange={set('fy')}/></Field><Field label={t('forms.bar_diameter')}><input required type="number" min="0.01" step="any" value={v.barDiameter} onChange={set('barDiameter')}/></Field>{v.type==='solid'&&<><Field label={t('forms.top_bar_count')}><input required type="number" min="1" value={v.top} onChange={set('top')}/></Field><Field label={t('forms.bottom_bar_count')}><input required type="number" min="1" value={v.bottom} onChange={set('bottom')}/></Field></>}{v.type==='hollow'&&<><Field label={t('forms.bottom_bar_count')}><input required type="number" min="1" value={v.bottom} onChange={set('bottom')}/></Field><Field label={t('forms.block_height')}><input required type="number" min="0.01" step="any" value={v.block} onChange={set('block')}/></Field></>}{v.type==='waffle'&&<><Field label={t('forms.bottom_bar_count')}><input required type="number" min="1" value={v.bottom} onChange={set('bottom')}/></Field><Field label={t('forms.rib_width')}><input required type="number" min="0.01" step="any" value={v.ribWidth} onChange={set('ribWidth')}/></Field><Field label={t('forms.rib_spacing')}><input required type="number" min="0.01" step="any" value={v.ribSpacing} onChange={set('ribSpacing')}/></Field></>}</FormSection><FormSection title={t('forms.area_loads')}>{['dead','live','wind','snow'].map(k=><Field key={k} label={t(`forms.${k}`)}><input type="number" step="0.01" value={v[k]} onChange={set(k)}/></Field>)}</FormSection><div className="form-actions"><button className="button button-primary" disabled={disabled}>{disabled?t('common.analyzing'):t('forms.run_slab')}</button></div></form>
}
