import { useEffect, useState } from 'react'
import sectionData from '../data/steel_sections_data.json'
import { Field, FormSection } from './workspace/FormControls'

function SteelForm({ column = false, onSubmit, disabled }) {
  const [v,setV]=useState({sectionType:'',sectionSize:'',steelGrade:'235',span:'',uniformLoad:'',axialLoad:'',length:'',kFactor:'1',supportType:'Simply Supported',boundaryCondition:'Pinned-Pinned'})
  const [dimensions,setDimensions]=useState({depth:'',width:'',flangeThickness:'',webThickness:''})
  const set=k=>e=>setV(x=>({...x,[k]:e.target.value}))
  useEffect(()=>{const sec=sectionData[v.sectionType]?.[v.sectionSize];setDimensions(sec?{depth:sec.h||'',width:sec.b||'',flangeThickness:sec.tf||'',webThickness:sec.tw||''}:{depth:'',width:'',flangeThickness:'',webThickness:''})},[v.sectionType,v.sectionSize])
  const submit=e=>{e.preventDefault();const base={sectionType:v.sectionType,sectionSize:v.sectionSize,dimensions,steelGrade:Number(v.steelGrade)};onSubmit(column?{...base,axialLoad:Number(v.axialLoad),length:Number(v.length),kFactor:Number(v.kFactor),boundaryCondition:v.boundaryCondition}:{...base,span:Number(v.span),uniformLoad:Number(v.uniformLoad),supportType:v.supportType})}
  const sizes=Object.keys(sectionData[v.sectionType]||{})
  return <form onSubmit={submit}><FormSection title="Section and material"><Field label="Section type"><select required value={v.sectionType} onChange={set('sectionType')}><option value="">Select type</option>{Object.keys(sectionData).map(type=><option key={type}>{type}</option>)}</select></Field><Field label="Section size"><select required value={v.sectionSize} onChange={set('sectionSize')} disabled={!v.sectionType}><option value="">Select size</option>{sizes.map(size=><option key={size}>{size}</option>)}</select></Field><Field label="Steel grade fy (MPa)"><input required type="number" min="0.01" step="any" value={v.steelGrade} onChange={set('steelGrade')}/></Field><Field label="Depth h (mm)"><input readOnly value={dimensions.depth}/></Field><Field label="Width b (mm)"><input readOnly value={dimensions.width}/></Field><Field label="Flange thickness tf (mm)"><input readOnly value={dimensions.flangeThickness}/></Field><Field label="Web thickness tw (mm)"><input readOnly value={dimensions.webThickness}/></Field></FormSection>{column?<FormSection title="Column actions and boundary"><Field label="Axial load (kN)"><input required type="number" min="0" value={v.axialLoad} onChange={set('axialLoad')}/></Field><Field label="Column length (mm)"><input required type="number" min="0.01" step="any" value={v.length} onChange={set('length')}/></Field><Field label="Boundary condition"><select value={v.boundaryCondition} onChange={set('boundaryCondition')}><option>Pinned-Pinned</option><option>Fixed-Fixed</option><option>Fixed-Free</option><option>Custom</option></select></Field><Field label="Effective length factor K"><input required type="number" min="0.01" step="0.01" value={v.kFactor} onChange={set('kFactor')}/></Field></FormSection>:<FormSection title="Beam actions and supports"><Field label="Beam span (mm)"><input required type="number" min="0.01" step="any" value={v.span} onChange={set('span')}/></Field><Field label="Uniform load (kN/m)"><input required type="number" value={v.uniformLoad} onChange={set('uniformLoad')}/></Field><Field label="Support type"><select value={v.supportType} onChange={set('supportType')}><option>Simply Supported</option><option>Fixed</option><option>Cantilever</option><option>Continuous</option></select></Field></FormSection>}<div className="form-actions"><button className="button button-primary" disabled={disabled}>{disabled?'Analyzing…':`Run steel ${column?'column':'beam'} analysis`}</button></div></form>
}
export function SteelBeamForm(props){return <SteelForm {...props}/>} export function SteelColumnForm(props){return <SteelForm {...props} column/>}