"""P9 initial identity, ownership, project, and immutable-run schema."""
from alembic import op
import sqlalchemy as sa
revision="20260922_p9_initial"
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("email",sa.String(320),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("display_name",sa.String(120),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("email",name="uq_users_email"));op.create_index("ix_users_email","users",["email"],unique=True)
    op.create_table("organizations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(160),nullable=False),sa.Column("created_by_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_organizations_created_by_user_id","organizations",["created_by_user_id"])
    op.create_table("organization_memberships",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("role",sa.String(16),nullable=False),sa.Column("created_by_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("organization_id","user_id",name="uq_membership_organization_user"));op.create_index("ix_memberships_org","organization_memberships",["organization_id"]);op.create_index("ix_memberships_user","organization_memberships",["user_id"])
    op.create_table("projects",sa.Column("id",sa.String(36),primary_key=True),sa.Column("organization_id",sa.String(36),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("description",sa.Text()),sa.Column("state",sa.String(16),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_by_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("updated_by_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_projects_organization_id","projects",["organization_id"]);op.create_index("ix_projects_organization_created","projects",["organization_id","created_at"])
    op.create_table("engine_versions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("engine_id",sa.String(120),nullable=False),sa.Column("engine_version",sa.String(80),nullable=False),sa.Column("repository_commit_sha",sa.String(80),nullable=False),sa.Column("analysis_run_schema_version",sa.String(80),nullable=False),sa.Column("report_schema_version",sa.String(80),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("engine_id","engine_version","repository_commit_sha","analysis_run_schema_version","report_schema_version",name="uq_engine_version_identity"))
    op.create_table("persistent_analysis_runs",sa.Column("run_id",sa.String(36),primary_key=True),sa.Column("project_id",sa.String(36),sa.ForeignKey("projects.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_by_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("analysis_kind",sa.String(20),nullable=False),sa.Column("code_family_id",sa.String(40),nullable=False),sa.Column("verification_status",sa.String(48),nullable=False),sa.Column("analysis_run_schema_version",sa.String(80),nullable=False),sa.Column("engine_version_id",sa.String(36),sa.ForeignKey("engine_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("record_json",sa.Text(),nullable=False),sa.Column("input_sha256",sa.String(64),nullable=False),sa.Column("result_sha256",sa.String(64),nullable=False),sa.Column("record_sha256",sa.String(64),nullable=False));op.create_index("ix_runs_project_created","persistent_analysis_runs",["project_id","created_at"])
    op.create_table("report_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("run_id",sa.String(36),sa.ForeignKey("persistent_analysis_runs.run_id",ondelete="RESTRICT"),nullable=False),sa.Column("project_id",sa.String(36),sa.ForeignKey("projects.id",ondelete="RESTRICT"),nullable=False),sa.Column("generated_by_user_id",sa.String(36),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("report_schema_version",sa.String(80),nullable=False),sa.Column("content_sha256",sa.String(64)),sa.Column("generated_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_report_records_run_id","report_records",["run_id"]);op.create_index("ix_report_records_project_id","report_records",["project_id"])
def downgrade():
    op.drop_table("report_records");op.drop_table("persistent_analysis_runs");op.drop_table("engine_versions");op.drop_table("projects");op.drop_table("organization_memberships");op.drop_table("organizations");op.drop_table("users")
