import { useCallback, useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { createProject, getOrganizations, getProjectRuns, getProjects } from '../api/client'
import { useAuth } from '../context/AuthContext'
import { useProject } from '../context/ProjectContext'
import { ErrorPanel, LoadingState, StatusNotice } from '../components/workspace/StatusNotice'

export default function Projects() {
  const { t } = useTranslation(); const auth = useAuth(); const { activeProjectId, selectProject } = useProject(); const [projects, setProjects] = useState([]); const [organizations, setOrganizations] = useState([]); const [runs, setRuns] = useState([]); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState(null); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [availableProjects, availableOrganizations] = await Promise.all([getProjects(), getOrganizations()]); setProjects(availableProjects); setOrganizations(availableOrganizations); const selected = availableProjects.find(item => item.id === activeProjectId) || availableProjects[0]; if (selected) { if (activeProjectId !== selected.id) selectProject(selected.id); setRuns(await getProjectRuns(selected.id)) } else { selectProject(null); setRuns([]) } } catch (reason) { setError(reason) } finally { setLoading(false) } }, [activeProjectId, selectProject])
  useEffect(() => { if (auth.authenticated) load() }, [auth.authenticated, load])
  if (!auth.loading && !auth.authenticated) return <Navigate to="/sign-in" replace />
  const select = async id => { selectProject(id); setError(null); try { setRuns(await getProjectRuns(id)) } catch (reason) { if (reason.status === 404) selectProject(null); setRuns([]); setError(reason) } }
  const submit = async event => { event.preventDefault(); if (!organizations[0]) return; setError(null); try { const item = await createProject({ organization_id: organizations[0].id, name, description: description || null }); setName(''); setDescription(''); selectProject(item.id); await load() } catch (reason) { setError(reason) } }
  const selected = projects.find(item => item.id === activeProjectId)
  return <section><header className="page-header"><div><p className="eyebrow">{t('projects.eyebrow')}</p><h1>{t('projects.title')}</h1><p>{t('projects.subtitle')}</p></div></header>{loading ? <LoadingState /> : <div className="workspace-grid"><aside className="workspace-sidebar"><section className="panel control-stack"><h2>{t('projects.create')}</h2><form className="control-stack" onSubmit={submit}><label className="field"><span className="field-label">{t('projects.name')}</span><input required value={name} onChange={event => setName(event.target.value)} /></label><label className="field"><span className="field-label">{t('projects.description')}</span><textarea value={description} onChange={event => setDescription(event.target.value)} /></label><button className="button button-primary">{t('projects.create')}</button></form></section><StatusNotice tone="warning" title={t('identity.foundation_title')}><p>{t('projects.local_notice')}</p></StatusNotice></aside><div className="workspace-content"><section className="panel"><h2>{t('projects.accessible')}</h2>{projects.length ? <div className="model-list">{projects.map(item => <button type="button" key={item.id} className={`model-row button ${item.id === activeProjectId ? 'button-primary' : 'button-secondary'}`} onClick={() => select(item.id)}><span>{item.name}</span><code>{item.id}</code></button>)}</div> : <p>{t('projects.none')}</p>}</section>{selected && <section className="panel"><h2>{selected.name}</h2><p>{selected.description || t('projects.no_description')}</p><p><strong>{t('projects.active')}</strong> <code>{selected.id}</code></p><h3>{t('projects.recent_runs')}</h3>{runs.length ? <div className="table-scroll"><table className="engineering-table"><thead><tr><th>{t('projects.run')}</th><th>{t('projects.kind')}</th><th>{t('projects.code')}</th><th>{t('projects.status')}</th></tr></thead><tbody>{runs.map(run => <tr key={run.run_id}><td><code>{run.run_id}</code></td><td>{run.analysis_kind}</td><td>{run.code_family_id}</td><td><code>{run.verification_status}</code></td></tr>)}</tbody></table></div> : <p>{t('projects.no_runs')}</p>}</section>}{error && <ErrorPanel error={error} onRetry={load} />}</div></div>}</section>
}
